ServerEvents.recipes(event => {
    // Simulated Egg recipe
    event.recipes.gtceu.assembler('kubejs_simulated_egg')
        .circuit(32)
        .itemInputs('8x gtceu:polyethylene_plate')
        .inputFluids(Fluid.of('mob_grinding_utils:fluid_xp 1000'))
        .itemOutputs('kubejs:simulated_egg')
        .duration(20*30)
        .EUt(GTValues.VA[GTValues.MV])

    // Spawn Eggs
    let egg = (itemName, ingredient, output) => {
        event.recipes.gtceu.assembler(`kubejs_${itemName}_spawn_egg`)
            .circuit(32)
            .itemInputs('kubejs:simulated_egg', ingredient)
            .itemOutputs(output)
            .duration(20*20)
            .EUt(GTValues.VA[GTValues.MV])
    }

    egg('allay', 'kubejs:mana_core', 'minecraft:allay_spawn_egg')
    egg('axolotl', 'minecraft:water_bucket', 'minecraft:axolotl_spawn_egg')
    egg('bat', 'minecraft:netherrack', 'minecraft:bat_spawn_egg')
    egg('bee', 'minecraft:honeycomb', 'minecraft:bee_spawn_egg')
    egg('blaze', 'minecraft:blaze_rod', 'minecraft:blaze_spawn_egg')
    egg('camel', 'minecraft:sand', 'minecraft:camel_spawn_egg')
    egg('cat', 'minecraft:clay_ball', 'minecraft:cat_spawn_egg')
    egg('cave_spider', 'minecraft:spider_eye', 'minecraft:cave_spider_spawn_egg')
    egg('chicken', 'minecraft:feather', 'minecraft:chicken_spawn_egg')
    egg('cod', 'minecraft:glass_bottle', 'minecraft:cod_spawn_egg')
    egg('cow', 'minecraft:hay_block', 'minecraft:cow_spawn_egg')
    egg('creeper', 'minecraft:tnt', 'minecraft:creeper_spawn_egg')
    egg('dolphin', 'minecraft:cod', 'minecraft:dolphin_spawn_egg')
    egg('donkey', 'minecraft:chest', 'minecraft:donkey_spawn_egg')
    egg('drowned', 'minecraft:potion', 'minecraft:drowned_spawn_egg')
    egg('elder_guardian', 'minecraft:prismarine_crystals', 'minecraft:elder_guardian_spawn_egg')
    egg('enderman', 'minecraft:ender_pearl', 'minecraft:enderman_spawn_egg')
    egg('endermite', 'gtceu:glowstone_plate', 'minecraft:endermite_spawn_egg')
    egg('evoker', 'minecraft:book', 'minecraft:evoker_spawn_egg')
    egg('fox', 'minecraft:apple', 'minecraft:fox_spawn_egg')
    egg('frog', 'minecraft:mud', 'minecraft:frog_spawn_egg')
    egg('ghast', 'minecraft:ghast_tear', 'minecraft:ghast_spawn_egg')
    egg('glow_squid', 'minecraft:glowstone', 'minecraft:glow_squid_spawn_egg')
    egg('goat', 'minecraft:snowball', 'minecraft:goat_spawn_egg')
    egg('guardian', 'minecraft:prismarine_shard', 'minecraft:guardian_spawn_egg')
    egg('hoglin', 'minecraft:gold_ingot', 'minecraft:hoglin_spawn_egg')
    egg('horse', 'minecraft:leather', 'minecraft:horse_spawn_egg')
    egg('husk', 'gtceu:small_bone_dust', 'minecraft:husk_spawn_egg')
    egg('iron_golem', 'minecraft:iron_block', 'minecraft:iron_golem_spawn_egg')
    egg('llama', 'minecraft:wheat', 'minecraft:llama_spawn_egg')
    egg('magma_cube', 'minecraft:magma_cream', 'minecraft:magma_cube_spawn_egg')
    egg('mooshroom', 'minecraft:melon_slice', 'minecraft:mooshroom_spawn_egg')
    egg('mule', 'minecraft:trapped_chest', 'minecraft:mule_spawn_egg')
    egg('ocelot', 'minecraft:cookie', 'minecraft:ocelot_spawn_egg')
    egg('panda', 'minecraft:paper', 'minecraft:panda_spawn_egg')
    egg('parrot', 'minecraft:wheat_seeds', 'minecraft:parrot_spawn_egg')
    egg('phantom', 'minecraft:phantom_membrane', 'minecraft:phantom_spawn_egg')
    egg('pig', 'minecraft:carrot', 'minecraft:pig_spawn_egg')
    egg('piglin', 'minecraft:gold_nugget', 'minecraft:piglin_spawn_egg')
    egg('piglin_brute', 'minecraft:iron_axe', 'minecraft:piglin_brute_spawn_egg')
    egg('pillager', 'minecraft:diamond', 'minecraft:pillager_spawn_egg')
    egg('polar_bear', 'minecraft:snow_block', 'minecraft:polar_bear_spawn_egg')
    egg('pufferfish', 'minecraft:pufferfish', 'minecraft:pufferfish_spawn_egg')
    egg('ravager', 'minecraft:iron_nugget', 'minecraft:ravager_spawn_egg')
    egg('rabbit', 'minecraft:redstone', 'minecraft:rabbit_spawn_egg')
    egg('salmon', 'minecraft:pufferfish', 'minecraft:salmon_spawn_egg')
    egg('sheep', '#forge:wool', 'minecraft:sheep_spawn_egg')
    egg('shulker', 'minecraft:shulker_shell', 'minecraft:shulker_spawn_egg')
    egg('silverfish', 'gtceu:silver_ingot', 'minecraft:silverfish_spawn_egg')
    egg('skeleton', 'minecraft:bone', 'minecraft:skeleton_spawn_egg')
    egg('skeleton_horse', 'minecraft:bone_block', 'minecraft:skeleton_horse_spawn_egg')
    egg('slime', 'minecraft:slime_ball', 'minecraft:slime_spawn_egg')
    egg('sniffer', 'minecraft:stick', 'minecraft:sniffer_spawn_egg')
    egg('snow_golem', 'minecraft:ice', 'minecraft:snow_golem_spawn_egg')
    egg('spider', 'minecraft:string', 'minecraft:spider_spawn_egg')
    egg('squid', 'botania:black_petal', 'minecraft:squid_spawn_egg')
    egg('stray', 'minecraft:rotten_flesh', 'minecraft:stray_spawn_egg')
    egg('strider', 'minecraft:lava_bucket', 'minecraft:strider_spawn_egg')
    egg('tadpole', 'minecraft:packed_mud', 'minecraft:tadpole_spawn_egg')
    egg('tropical_fish', 'minecraft:tropical_fish', 'minecraft:tropical_fish_spawn_egg')
    egg('turtle', 'gtceu:steel_ingot', 'minecraft:turtle_spawn_egg')
    egg('vex', 'minecraft:iron_sword', 'minecraft:vex_spawn_egg')
    egg('villager', '16x minecraft:emerald', 'minecraft:villager_spawn_egg')
    egg('vindicator', 'minecraft:bone_meal', 'minecraft:vindicator_spawn_egg')
    egg('warden', '64x gtceu:titanium_ingot', 'minecraft:warden_spawn_egg')
    egg('witch', 'minecraft:sugar', 'minecraft:witch_spawn_egg')
    // egg('wither', '64x minecraft:stainless_steel_ingot', 'minecraft:wither_spawn_egg')
    egg('wither_skeleton', 'minecraft:wither_skeleton_skull', 'minecraft:wither_skeleton_spawn_egg')
    egg('wolf', 'minecraft:cooked_beef', 'minecraft:wolf_spawn_egg')
    egg('zoglin', 'minecraft:raw_beef', 'minecraft:zoglin_spawn_egg')
    egg('zombie', 'gtceu:iron_plate', 'minecraft:zombie_spawn_egg')
    egg('zombie_horse', 'minecraft:magma_block', 'minecraft:zombie_horse_spawn_egg')
    egg('zombie_villager', 'gtceu:emerald_plate', 'minecraft:zombie_villager_spawn_egg')
    egg('zombified_piglin', 'gtceu:emerald_dust', 'minecraft:zombified_piglin_spawn_egg')

    // aether
    egg('aechor_plant', 'aether:aechor_petal', 'aether:aechor_plant_spawn_egg')
    egg('aer_bunny', 'aether:holystone', 'aether:aerbunny_spawn_egg')
    egg('aerwhale', 'gtceu:zanite_gem', 'aether:aerwhale_spawn_egg')
    egg('blue_swet', 'aether:swet_ball', 'aether:blue_swet_spawn_egg')
    egg('cockatrice', 'gtceu:ambrosium_gem', 'aether:cockatrice_spawn_egg')
    egg('evil_whirlwind', 'gtceu:zanite_plate', 'aether:evil_whirlwind_spawn_egg')
    egg('fire_minion', 'gtceu:zanite_block', 'aether:fire_minion_spawn_egg')
    egg('flying_cow', 'aether:cold_aercloud', 'aether:flying_cow_spawn_egg')
    egg('golden_swet', 'aether:golden_amber', 'aether:golden_swet_spawn_egg')
    egg('mimic', 'gtceu:ambrosium_block', 'aether:mimic_spawn_egg')
    egg('moa', 'aether:mossy_holystone', 'aether:moa_spawn_egg')
    egg('phyg', 'aether:aether_dirt', 'aether:phyg_spawn_egg')
    egg('sentry', 'aether:quicksoil', 'aether:sentry_spawn_egg')
    egg('sheepuff', 'aether:aerogel', 'aether:sheepuff_spawn_egg')
    egg('whirlwind', 'aether:zanite_ring', 'aether:whirlwind_spawn_egg')
    egg('valkyrie', 'aether:life_shard', 'aether:valkyrie_spawn_egg')
    egg('zephyr', 'aether:golden_ring', 'aether:zephyr_spawn_egg')

    // thermal
    egg('basalz', 'thermal:basalz_powder', 'thermal:basalz_spawn_egg')
    egg('blizz', 'thermal:blizz_powder', 'thermal:blizz_spawn_egg')
    egg('blitz', 'thermal:blitz_powder', 'thermal:blitz_spawn_egg')


        
})